CREATE TABLE SBR.MDSR_PV_UPDEATE_ERR
(
  VALUE_DOMAIN_ID   VARCHAR2(50 BYTE),
  VALUE_DOMAIN_VER  VARCHAR2(5 BYTE),
  LONGNAME          VARCHAR2(100 BYTE),
  TYPE              VARCHAR2(50 BYTE),
  EXISTING_PV       VARCHAR2(1100 BYTE),
  DATE_MODIFIED     VARCHAR2(50 BYTE),
  MODIFIED_BY       VARCHAR2(50 BYTE),
  NEW_PV            VARCHAR2(255 BYTE),
  COMMENTS          VARCHAR2(2000 BYTE),
  DATE_PROCESSED    DATE
)