OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\JIRA-517\VD_PV_QA.csv' "str '\r'"
INTO TABLE "SBR"."MDSR_PV_UP_ENDDATE_TEMP"
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( PV_VALUE  "TRIM(:PV_VALUE)", 
VD_ID "TRIM(:VD_ID)",
VD_VER,
BEGIN_DATE,
END_DATE,
MODIFIED_BY

)