CREATE TABLE SBREXT.CT_QUEST_CONTENTS_EXT_BKUP
( QC_IDSEQ              CHAR(36 BYTE)           NOT NULL,
  PREFERRED_NAME        VARCHAR2(30 BYTE),
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  LONG_NAME             VARCHAR2(4000 BYTE)
)
/
CREATE TABLE SBREXT.CT_VALID_VALUES_ATT_EXT_BKUP
( QC_IDSEQ          CHAR(36 BYTE)               NOT NULL,
  MEANING_TEXT      VARCHAR2(2000 BYTE),
  DATE_MODIFIED     DATE,
  MODIFIED_BY       VARCHAR2(30 BYTE),
  DESCRIPTION_TEXT  VARCHAR2(2000 BYTE)
)
/
CREATE TABLE SBREXT.CT_FB_SPCHAR_ERROR_LOG
( SP_NAME              CHAR(36 BYTE)           NOT NULL,
  DATE_MODIFIED         DATE,
  ERROR_TEXT             VARCHAR2(4000 BYTE)
)
/
CREATE TABLE SBR.CT_FIX_PERMISSIBLE_VALUES
(
  PV_IDSEQ             CHAR(36 BYTE)            NOT NULL,
  VALUE                VARCHAR2(255 BYTE)       NOT NULL,
  SHORT_MEANING        VARCHAR2(255 BYTE)       NOT NULL,
  MEANING_DESCRIPTION  VARCHAR2(2000 BYTE),
  DATE_MODIFIED        DATE,
  MODIFIED_BY          VARCHAR2(30 BYTE),
  VM_IDSEQ             CHAR(36 BYTE)            NOT NULL
)
/
CREATE TABLE SBR.CT_FIX_VALUE_MEANINGS
( SHORT_MEANING         VARCHAR2(255 BYTE)      NOT NULL,
  DESCRIPTION           VARCHAR2(2000 BYTE),
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  VM_IDSEQ              CHAR(36 BYTE)           NOT NULL,
  PREFERRED_NAME        VARCHAR2(30 BYTE)       NOT NULL,
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)     NOT NULL,
  LONG_NAME             VARCHAR2(255 BYTE),
  VERSION               NUMBER                  NOT NULL,
  VM_ID                 NUMBER                  NOT NULL,
  CHANGE_NOTE           VARCHAR2(2000 BYTE)
)
grant select,insert  on SBREXT.CT_FB_SPCHAR_ERROR_LOG to SBR
/