OPTIONS ( ERRORS= 300, SKIP=1)
LOAD DATA
INFILE 'DBA_PATH\Origin.csv' "Str '\r'"
INTO TABLE "SBREXT"."ORIGIN_TEMP"
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(SRC_NAME char(1000),
DESCRIPTION char(4000))

