DROP table SBREXT.MDSR_FB_XML_REPORT_ERR ;
DROP table SBREXT.MDSR_FB_XML_TEMP ;

DROP MATERIALIZED VIEW  SBREXT.MDSR_FB_QUEST_MODULE_MVW ;
DROP MATERIALIZED VIEW  SBREXT.MDSR_FB_QUESTION_MVW ;
DROP MATERIALIZED VIEW  SBREXT.MDSR_FB_VALID_VALUE_MVW;

drop type MDSR_FB_FORM_XML_T1;
drop type MDSR_FB_PROTOCOL_XML_LIST_T; 
drop type  MDSR_FB_PROTOCOL_XML_T;

drop type MDSR_FB_MODULE_XML_LIST_T1;
drop type MDSR_FB_MODULE_XML_T1;

drop type MDSR_FB_QUESTION_XML_LIST_T1;
drop type MDSR_FB_QUESTION_XML_T1;

drop type MDSR_FB_DATA_EL_XML_T1;
drop type MDSR_FB_VV_XML_LIST_T1;
drop type MDSR_FB_VV_XML_T1;
drop type MDSR_FB_VV_VM_XML_T1; 

drop type MDSR_FB_COM_DE_DR_XML_LIST_T1;
drop type MDSR_FB_COM_DE_DR_XML_T1;
drop type MDSR_FB_DE_DR_XML_T1;
drop type MDSR_FB_UseCat_XML;
drop type MDSR_FB_VD_DR_XML_T1;
drop type MDSR_FB_VDC_DR_XML_T1 ;
drop type MDSR_FB_VD_XML_T1;
drop type MDSR_FB_RD_XML_LIST_T1;
drop type MDSR_FB_RD_XML_T1;

drop type MDSR_FB_PV_XML_LIST_T1;
drop type MDSR_FB_PV_XML_T1;
drop type MDSR_FB_VM_XML_T1;

drop type MDSR_FB_VDCon_XML_LIST_T1;
drop type MDSR_FB_VDCon_XML_T1;
drop type MDSR_FB_DEFIN_XML_LIST_T1;
drop type MDSR_FB_DEFIN_XML_T1;
drop type MDSR_FB_DESIGN_XML_LIST_T1;
drop type MDSR_FB_DESIGN_XML_T1;

drop type MDSR_FB_FORM_CL_XML_LIST_T1;
drop type MDSR_FB_FORM_CL_XML_T1;
drop type MDSR_FB_FORM_CLI_XML_T1;