/*
drop VIEW SBREXT.MDSR_CONTEXT_GROUP_749_VW;
drop VIEW SBREXT.MDSR_DE_XML_749_VW;
drop TABLE SBREXT.MDSR_CDE_XML_REPORT_ERR;
drop TABLE SBREXT.MDSR_CDE_XML_TEMP;
DROP TYPE SBREXT.MDSR_CDE_749_LIST_T;
DROP TYPE SBREXT.MDSR_CDE_749_T;
DROP TYPE SBREXT.MDSR_749_VALUEDOMAIN_LIST_T;
DROP TYPE SBREXT.MDSR_749_VALUEDOMAIN_T;
DROP TYPE SBREXT.MDSR_749_PVS_LIST_T;
DROP TYPE SBREXT.MDSR_749_PV_ITEM_T;
DROP TYPE SBREXT.MDSR_749_ALTERNATENAM_LIST_T;
DROP TYPE SBREXT.MDSR_749_ALTERNATENAME_ITEM_T;
DROP TYPE SBREXT.MDSR_749_REFERENCEDOC_LIST_T;
DROP TYPE SBREXT.MDSR_749_REFERENCEDOCUMENT_T;*/
DROP VIEW SBREXT.DE_CDE1_XML_GENERATOR_749VW;
DROP TYPE SBREXT.CDEBROWSER_VD_T749;
DROP TYPE SBREXT.MDSR_749_PV_VD_LIST_T;
DROP TYPE SBREXT.MDSR_749_PV_VD_ITEM_T;
DROP TYPE SBREXT.MDSR_749_ALTERNATENAM_LIST_T;
DROP TYPE SBREXT.MDSR_749_ALTERNATENAME_ITEM_T; 



