CREATE OR REPLACE FORCE VIEW MDSR_STANDARD_FORM_CDE_AGR

as SELECT MODULE_TYPE,
   MODULE_ORDER,
   CDE_ID,
   DE_VERSION,DE_NAME, LISTAGG(FORM_ID_VERSION, '::') WITHIN GROUP (ORDER BY FORM_ID_VERSION) AS FORM_ID,LISTAGG(FORM_NAME, '::') WITHIN GROUP (ORDER BY FORM_ID_VERSION) AS FORM_NAME
FROM MDSR_STANDARD_FORM_CDE_TYPE GROUP BY MODULE_TYPE,
   MODULE_ORDER,
   CDE_ID,
   DE_VERSION,
   DE_NAME
   order by  MODULE_ORDER,
   CDE_ID;


