select count(*) from SBREXT.MDSR_VM_DUP_REF  R
,SBREXT.CON_DERIVATION_RULES_EXT CN
where R.CONDR_IDSEQ=CN.CONDR_IDSEQ
AND instr(CN.NAME,'C17649')>0;

select * from SBREXT.MDSR_VM_DUP_REF

select name,long_name from SBREXT.MDSR_VM_DUP_REF  R
,SBREXT.CON_DERIVATION_RULES_EXT CN
where R.CONDR_IDSEQ=CN.CONDR_IDSEQ
AND instr(CN.NAME,'C17649')>0;


select* from SBREXT.CON_DERIVATION_RULES_EXT CN
where instr(CN.NAME,'C17649')>0;


select DISTINCT DER.CONDR_IDSEQ,NAME
--select COUNT(*)
FROM
SBREXT.CON_DERIVATION_RULES_EXT DER,
(select DISTINCT CONDR_IDSEQ
FROM(
select COUNT(*),VM.CONDR_IDSEQ from SBR.VALUE_MEANINGS VM,
SBREXT.CON_DERIVATION_RULES_EXT DER
 where   VM.CONDR_IDSEQ=DER.CONDR_IDSEQ 
 AND  UPPER(ASL_NAME) not like '%RETIRED%' 
 AND instr(DER.NAME,'C45255')=0
  GROUP BY VM.CONDR_IDSEQ HAVING COUNT(*)>1)
MINUS
(select DISTINCT CONDR_IDSEQ
FROM(
select   FIN_VM ,VM_ID,VM_NAME,CONCEPT_NAME,CONDR_IDSEQ,VM_IDSEQ from
(
select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,VM_NAME,CONCEPT_NAME,CONDR_IDSEQ,VM_IDSEQ from
(
select VM_ID,VM_IDSEQ,VM.LONG_NAME VM_NAME,CN.LONG_NAME CONCEPT_NAME,VM.CONDR_IDSEQ
from SBR.VALUE_MEANINGS VM,
SBREXT.CON_DERIVATION_RULES_EXT DER,
SBREXT.CONCEPTS_EXT CN,
(
 select COUNT(*),CONDR_IDSEQ from SBR.VALUE_MEANINGS VM
 where   UPPER(ASL_NAME) not like '%RETIRED%' AND CONDR_IDSEQ is not null
 GROUP BY CONDR_IDSEQ HAVING COUNT(*)>1
 )DUP
 where   VM.CONDR_IDSEQ=DER.CONDR_IDSEQ
 AND VM.CONDR_IDSEQ=DUP.CONDR_IDSEQ
 and DER.NAME=CN.PREFERRED_NAME
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%'
 AND TRIM(UPPER(VM.LONG_NAME)) =TRIM(UPPER(CN.LONG_NAME))
 AND instr(DER.NAME,'C45255')=0
 ))
 where FIN_VM=VM_ID
 
UNION  
 
 select   FIN_VM ,VM_ID,VM_NAME,CONCEPT_NAME,CONDR_IDSEQ,VM_IDSEQ from
(
select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,VM_NAME,CONCEPT_NAME,CONDR_IDSEQ,VM_IDSEQ from
(
 SELECT VM_ID,VM_IDSEQ,trim(UPPER(CONCEPT_NAME))CONCEPT_NAME,trim(UPPER(LONG_NAME)) VM_NAME,VM.CONDR_IDSEQ,trim(UPPER(vm.DESCRIPTION)) VM_DESCRIPTION
FROM  SBR.VALUE_MEANINGS VM,
(SELECT M.CONDR_IDSEQ,name, LISTAGG(M.LONG_NAME,' ') WITHIN GROUP (ORDER BY M.ELM_ORDER) as CONCEPT_NAME
FROM  (select CONDR_IDSEQ,name,spl.preferred_name,ELM_ORDER,LONG_NAME
from
(select distinct
 CONDR_IDSEQ,name,
 trim(regexp_substr(name, '[^:]+', 1, levels.column_value)) as preferred_name,levels.column_value ELM_ORDER
from 
 (select *from SBREXT.CON_DERIVATION_RULES_EXT 
 
 where  instr(name,':')>0) t,
 table(cast(multiset(select level from dual connect by level <= length (regexp_replace(t.name, '[^:]+')) + 1) as sys.OdciNumberList))
  levels) spl,
  sbrext.concepts_ext  c
  where spl.preferred_name=c.preferred_name) M
GROUP BY name,M.CONDR_IDSEQ)VW,
 (select count(*),CONDR_IDSEQ from SBR.VALUE_MEANINGS VM 
 where  UPPER(ASL_NAME) not like '%RETIRED%'
 having count(*)>1GROUP BY CONDR_IDSEQ )DR

where    VW.CONDR_IDSEQ=VM.CONDR_IDSEQ
AND  VW.CONDR_IDSEQ=DR.CONDR_IDSEQ
and UPPER(ASL_NAME) not like '%RETIRED%'
and trim(UPPER(VM.LONG_NAME))=trim(UPPER(CONCEPT_NAME))
and instr(NAME,'C45255')=0
 ))
 where FIN_VM=VM_ID))) VW
 where VW.CONDR_IDSEQ=DER.CONDR_IDSEQ
 AND  instr(DER.NAME,':')>0
 ORDER BY 1,2 desc ;
 
select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ, CONCEPTS_CODE,VM_NAME,CONDR_IDSEQ,'FINAL',
SINON from
( 
 select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,CONCEPTS_CODE,CONDR_IDSEQ,VM_IDSEQ ,VM_NAME,SINON from
(
 select NRF.CONDR_IDSEQ,NRF.NAME CONCEPTS_CODE,VM_ID,VM_IDSEQ,VM.LONG_NAME VM_NAME 
 ,SBREXT.MDSR_GET_CONCEPT_SYN(NRF.NAME,vm.LONG_NAME) SINON
 from
 SBR.VALUE_MEANINGS VM,
 ((select CONDR_IDSEQ,NAME from
 (select count(*),VM.CONDR_IDSEQ,NAME from SBR.VALUE_MEANINGS VM ,
 SBREXT.CON_DERIVATION_RULES_EXT  X
 where  X.CONDR_IDSEQ=VM.CONDR_IDSEQ 
 AND  instr(NAME,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 and instr(name,'C45255')=0 
 having count(*)>1GROUP BY VM.CONDR_IDSEQ,NAME ))
minus
select distinct CONDR_IDSEQ,CONCEPTS_CODE 
 FROM SBREXT.MDSR_VM_DUP_REF where instr(CONCEPTS_CODE,'C45255')=0
 AND instr(CONCEPTS_CODE,':')=0
 ) NRF
 where  NRF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 and (ASL_NAME) not like '%RETIRED%'
 AND SBREXT.MDSR_GET_CONCEPT_SYN(NRF.NAME,vm.LONG_NAME)=1)
 )
 WHERE FIN_VM=VM_ID
ORDER BY CONCEPTS_CODE,FIN_VM,VM_ID desc;


/***Find Final VM**/
(FROM
select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ, CONCEPTS_CODE,VM_NAME,CONDR_IDSEQ
from
 (select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,CONCEPTS_CODE,CONDR_IDSEQ,VM_IDSEQ ,VM_NAME from

 (select NRF.CONDR_IDSEQ,NRF.NAME CONCEPTS_CODE,VM_ID,VM_IDSEQ,VM.LONG_NAME VM_NAME 
 
 from
 SBR.VALUE_MEANINGS VM,
 ((select CONDR_IDSEQ,NAME from
 (select count(*),VM.CONDR_IDSEQ,NAME from SBR.VALUE_MEANINGS VM ,
 SBREXT.CON_DERIVATION_RULES_EXT  X
 where  X.CONDR_IDSEQ=VM.CONDR_IDSEQ 
 AND  instr(NAME,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 and instr(name,'C45255')=0 
 having count(*)>1GROUP BY VM.CONDR_IDSEQ,NAME ))
minus
select distinct CONDR_IDSEQ,CONCEPTS_CODE 
 FROM SBREXT.MDSR_VM_DUP_REF where instr(CONCEPTS_CODE,'C45255')=0
 AND instr(CONCEPTS_CODE,':')=0
 ) NRF
 where  NRF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 and (ASL_NAME) not like '%RETIRED%'
 AND SBREXT.MDSR_GET_CONCEPT_SYN(NRF.NAME,vm.LONG_NAME)=1))

 WHERE FIN_VM=VM_ID
 MINUS
 select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ, CONCEPTS_CODE,long_NAME,CONDR_IDSEQ
 FROM SBREXT.MDSR_VM_DUP_REF)
ORDER BY CONCEPTS_CODE,FIN_VM,VM_ID desc;



exec SBREXT.MDSR_INSERT_VM_FINAL_DUP_REF;

select count(*) FROM SBREXT.MDSR_VM_DUP_REF where proc is  null;--( is not 2343)(2499)
select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ, CONCEPTS_CODE,long_NAME,CONDR_IDSEQ,PROC,CONCEPTS_NAME
 FROM SBREXT.MDSR_VM_DUP_REF where proc is not null and CONCEPTS_NAME like 'SYNO%'
 order by CONCEPTS_NAME desc;
 
 
 
 select   FIN_VM ,FIN_IDSEQ,VM.VM_ID,VM.VM_IDSEQ, CONCEPTS_CODE,RF.LONG_NAME,VM.long_NAME,VM.CONDR_IDSEQ,CONCEPTS_NAME
 FROM SBREXT.MDSR_VM_DUP_REF RF,
 SBR.VALUE_MEANINGS VM
 WHERE RF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND instr(CONCEPTS_CODE,'C45255')=0
 AND instr(CONCEPTS_CODE,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 AND FIN_VM<>VM.VM_ID
 AND SBREXT.MDSR_GET_CONCEPT_SYN(RF.CONCEPTS_CODE,vm.LONG_NAME)=1
 AND  proc is not null and CONCEPTS_NAME like 'SYNONYM%';
 
 select FIN_VM ,FIN_IDSEQ,VM.VM_ID,VM.VM_IDSEQ, CONCEPTS_CODE,RF.LONG_NAME,VM.long_NAME,VM.CONDR_IDSEQ,CONCEPTS_NAME
 FROM SBREXT.MDSR_VM_DUP_REF RF,
 SBR.VALUE_MEANINGS VM
 WHERE RF.CONDR_IDSEQ=VM.CONDR_IDSEQ 
 AND instr(CONCEPTS_CODE,'C45255')=0
 AND instr(CONCEPTS_CODE,':')>0
 AND CONCEPTS_NAME IS NULL
 AND trim(UPPER(RF.LONG_NAME))=trim(UPPER(VM.long_NAME))
  AND FIN_VM<>VM.VM_ID
 AND RF.PROC ='FINAL'