OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\JIRA-567\VM_SINGL_CONCEPTS.csv' "str '\r'" 
BADFILE 'C:\meta\JIRA-567\VM_SINGL_CONCEPTS.bad'
DISCARDFILE 'C:\meta\JIRA-567\VM_SINGL_CONCEPTS' 
INTO TABLE "SBREXT"."MDSR_CONDR_ID_CONCEPT_CODE"
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS                 
   (  CONDR_ID  CHAR(60) ,
    CONCEPT_CODE CHAR(100))