CREATE TABLE MDSR_CONCEPTS_SYNONYMS_TMP
(
  CODE          VARCHAR2(30 BYTE),
  CONCEPT_NAME  VARCHAR2(255 BYTE),
  SYNONYM_NAME  VARCHAR2(500 BYTE)
);
CREATE TABLE MDSR_CONCEPTS_SYNONYMS_LOAD
(
  CODE          VARCHAR2(130 BYTE),
  CONCEPT_NAME  VARCHAR2(255 BYTE),
  SYNONYM_NAME  VARCHAR2(500 BYTE),
  SYN VARCHAR2(5 BYTE)
);
--drop TABLE MDSR_CONCEPTS_SYNONYMS_LOAD;

select distinct CODE          ,
  CONCEPT_NAME  ,
  trim(UPPER(SYNONYM_NAME))
  from MDSR_CONCEPTS_SYNONYMS_LOAD where syn is not null
  order by code;
  
 insert into  MDSR_CONCEPTS_SYNONYMS_TMP
(
  CODE ,
  CONCEPT_NAME  ,
  SYNONYM_NAME
)
  
select distinct CODE          ,
  CONCEPT_NAME  ,
  trim(UPPER(SYNONYM_NAME))
  from MDSR_CONCEPTS_SYNONYMS_LOAD where syn is not null
  order by code;