(select RF.PROCESSED||' VM' PROCESSED ,FIN_VM,RF.CONDR_IDSEQ, RF.CONCEPTS_CODE,trim(UPPER(RF.CONCEPTS_NAME)),trim(UPPER(RF.LONG_NAME)) LONG_NAME ,trim(UPPER(RF.PREFERRED_DEFINITION))
from SBREXT.MDSR_VM_DUP_REF RF,
(select NRF.CONDR_IDSEQ,NRF.NAME CONCEPTS_CODE,VM_ID,trim(UPPER(C.LONG_NAME)) CONCEPTS_NAME,trim(UPPER(VM.LONG_NAME))VM_NAME, trim(UPPER(VM.PREFERRED_DEFINITION)) PREFERRED_DEFINITION
--VM_PREFERRED_DEFINITION 
from SBR.VALUE_MEANINGS VM,
  SBREXT.CONCEPTS_EXT C,
 (select a.CONDR_IDSEQ,a.NAME from
 (select count(*),VM.CONDR_IDSEQ,replace(NAME,'Rh Positive Blood Group','C76251') NAME from SBR.VALUE_MEANINGS VM ,
 SBREXT.CON_DERIVATION_RULES_EXT  X
 where  X.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND  instr(NAME,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 and instr(name,'C45255')=0
 having count(*)>1GROUP BY VM.CONDR_IDSEQ,NAME )a
) NRF
 where  NRF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND NRF.NAME=C.PREFERRED_NAME
 AND VM.ASL_NAME not like '%RETIRED%'

minus
 select CONDR_IDSEQ, CONCEPTS_CODE,VM_ID, trim(UPPER(CONCEPTS_NAME)),trim(UPPER(LONG_NAME)) ,trim(UPPER(RF.PREFERRED_DEFINITION)) 
 FROM SBREXT.MDSR_VM_DUP_REF RF
 where   instr(CONCEPTS_CODE,':')=0
 and instr(CONCEPTS_CODE,'C45255')=0)MS
 where MS.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND MS.CONCEPTS_CODE=RF.CONCEPTS_CODE
 AND trim(UPPER(MS.PREFERRED_DEFINITION))=trim(UPPER(RF.PREFERRED_DEFINITION))
 AND PROCESSED='FINAL')

UNION
(select 'Is it Duplicate of VM '||FIN_VM||' ?' PROCESSED,MS.VM_ID, MS.CONDR_IDSEQ,  MS.CONCEPTS_CODE,MS.CONCEPTS_NAME, MS.LONG_NAME,MS.PREFERRED_DEFINITION
 from SBREXT.MDSR_VM_DUP_REF RF,
(select NRF.CONDR_IDSEQ,NRF.NAME CONCEPTS_CODE,VM_ID,trim(UPPER(C.LONG_NAME)) CONCEPTS_NAME,trim(UPPER(VM.LONG_NAME)) LONG_NAME ,trim(UPPER(VM.PREFERRED_DEFINITION)) PREFERRED_DEFINITION 
from
 SBR.VALUE_MEANINGS VM,
  SBREXT.CONCEPTS_EXT C,
 (select a.CONDR_IDSEQ,a.NAME from
 (select count(*),VM.CONDR_IDSEQ,replace(NAME,'Rh Positive Blood Group','C76251') NAME from SBR.VALUE_MEANINGS VM ,
 SBREXT.CON_DERIVATION_RULES_EXT  X
 where  X.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND  instr(NAME,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 and instr(name,'C45255')=0
 having count(*)>1GROUP BY VM.CONDR_IDSEQ,NAME )a
) NRF
 where  NRF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND NRF.NAME=C.PREFERRED_NAME
 AND VM.ASL_NAME not like '%RETIRED%'
--  AND trim(UPPER(VM.LONG_NAME))<>trim(UPPER(C.LONG_NAME))
 --AND MDSR_CLEAN_VM_DUPLICATES.MDSR_GET_CONCEPT_SYNONYM(NRF.NAME,trim(UPPER(vm.LONG_NAME)))=0
minus
 select CONDR_IDSEQ, CONCEPTS_CODE,VM_ID, trim(UPPER(CONCEPTS_NAME)),trim(UPPER(LONG_NAME))  ,trim(UPPER(PREFERRED_DEFINITION))
 FROM SBREXT.MDSR_VM_DUP_REF RF
 where   instr(CONCEPTS_CODE,':')=0
 and instr(CONCEPTS_CODE,'C45255')=0)MS
  where MS.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND MS.CONCEPTS_CODE=RF.CONCEPTS_CODE
 AND PROCESSED='FINAL'
 AND trim(UPPER(MS.PREFERRED_DEFINITION))=trim(UPPER(RF.PREFERRED_DEFINITION)))
 order by CONCEPTS_CODE, CONDR_IDSEQ,PROCESSED;