CREATE OR REPLACE PACKAGE MDSR_CLEAN_VM_DUPLICATES AS 
   FUNCTION MDSR_GET_CONCEPT_SYNONYM(p_code IN VARCHAR2 ,p_NAME IN VARCHAR2)
   RETURN NUMBER;   
   PROCEDURE MDSR_CALL_NCI_WEBSERVICE; 
   PROCEDURE MDSR_INSERT_CONCEPT_SYN; 
   PROCEDURE MDSR_INSERT_VM_FINAL_DUP_REF; 
   --PROCEDURE increase_comm(employee_id NUMBER, comm_incr NUMBER); 
   
END MDSR_CLEAN_VM_DUPLICATES; 
/ 