CREATE OR REPLACE PACKAGE SBREXT.MDSR_CLEAN_VM_DUPLICATES AS 
    FUNCTION MDSR_GET_CONCEPT_SYNONYM(p_code IN VARCHAR2 ,p_NAME IN VARCHAR2)
    RETURN NUMBER;   
    PROCEDURE MDSR_CALL_NCI_WEBSERVICE; 
    PROCEDURE MDSR_INSERT_CONCEPT_SYN; 
    PROCEDURE MDSR_INSERT_VM_FINAL_DUP_REF; 
    PROCEDURE MDSR_CREATE_DUP_VM_DES_DEF;    
    PROCEDURE MDSR_CREATE_DUP_VM_CSI; 
    PROCEDURE MDSR_CHECK_FVM_DES_DEF_CSI;  
END MDSR_CLEAN_VM_DUPLICATES;
/