CREATE TABLE MDSR_CONCEPTS_SYNONYMS_TMP
(
  CODE          VARCHAR2(130 BYTE),
  CONCEPT_NAME  VARCHAR2(255 BYTE),
  SYNONYM_NAME  VARCHAR2(500 BYTE)
)
/
CREATE TABLE MDSR_CONCEPTS_SYNONYMS_LOAD
(
  CODE          VARCHAR2(130 BYTE),
  CONCEPT_NAME  VARCHAR2(255 BYTE),
  SYNONYM_NAME  VARCHAR2(500 BYTE),
  SYN VARCHAR2(5 BYTE)
)
/
exec SBREXT.MDSR_CLEAN_VM_DUPLICATES.MDSR_INSERT_CONCEPT_SYN;
insert into  MDSR_CONCEPTS_SYNONYMS_TMP values('C64525','EVERY OTHER DAY','EVERY TWO DAYS');
insert into  MDSR_CONCEPTS_SYNONYMS_TMP 
select distinct CONCEPTS_CODE,CONCEPTS_Name ,VM_NAME 
 FROM ( select* from 
(select NRF.CONDR_IDSEQ,NRF.NAME CONCEPTS_CODE,VM_ID,trim(UPPER(C.LONG_NAME)) CONCEPTS_NAME,trim(UPPER(VM.LONG_NAME)) VM_NAME from
 SBR.VALUE_MEANINGS VM,
  SBREXT.CONCEPTS_EXT C,
 (select a.CONDR_IDSEQ,a.NAME from
 (select count(*),VM.CONDR_IDSEQ,replace(NAME,'Rh Positive Blood Group','C76251') NAME from SBR.VALUE_MEANINGS VM ,
 SBREXT.CON_DERIVATION_RULES_EXT  X
 where  X.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND  instr(NAME,':')=0
 and (ASL_NAME) not like '%RETIRED%'
 and instr(name,'C45255')=0
 having count(*)>1GROUP BY VM.CONDR_IDSEQ,NAME )a
) NRF
 where  NRF.CONDR_IDSEQ=VM.CONDR_IDSEQ
 AND NRF.NAME=C.PREFERRED_NAME
 AND VM.ASL_NAME not like '%RETIRED%'
minus
 select CONDR_IDSEQ, CONCEPTS_CODE,VM_ID, trim(UPPER(CONCEPTS_NAME)),trim(UPPER(LONG_NAME))  
 FROM SBREXT.MDSR_VM_DUP_REF RF
 where   instr(CONCEPTS_CODE,':')=0
 and instr(CONCEPTS_CODE,'C45255')=0))RF
where CONCEPTS_CODE in ('C94226','C91213','C91215','C91245','C90025','C74601',
'C7318','C72884','C72729','C7281','C70696','C7281','C70543',
'C67388','C67381','C67329','C67329','C67329','C67329','C67350') and CONCEPTS_Name <>long_name 

select* from (
select*from  SBREXT.MDSR_CONCEPTS_SYNONYMS where instr(CODE,':')>0
minus
select*from MDSR_CONCEPTS_SYNONYMS_TMP)