 select *
from 
MDSR_VM_DUP_REF REF
where    UPPER(trim(LONG_NAME))='9 MONTHS' 
and CONDR_IDSEQ IS NULL;

select FIN_VM,FIN_IDSEQ,VM.version,VM.VM_ID,VM.long_name,VM.PREFERRED_DEFINITION,VM.VM_IDSEQ, VM.CONTE_IDSEQ
from SBR.VALUE_MEANINGS VM,
MDSR_VM_DUP_REF REF
where   VM.VM_IDSEQ=REF.VM_IDSEQ
and VM.CONDR_IDSEQ='F37D0428-BBB6-6787-E034-0003BA3F9857';



select count(*), VM.CONTE_IDSEQ
from SBR.VALUE_MEANINGS VM
where    VM.CONDR_IDSEQ='F37D0428-BBB6-6787-E034-0003BA3F9857'
group by VM.CONTE_IDSEQ;

select* from  SBR.DEFINITIONS;


select REF.FIN_VM, VM.VM_IDSEQ,REF.VM_IDSEQ,VM.ASL_NAME
--select distinct VM.ASL_NAME
from SBR.VALUE_MEANINGS VM,
MDSR_VM_DUP_REF REF
where   VM.VM_ID=REF.VM_ID--REF.FIN_VM--

and VM.ASL_NAME='RETIRED ARCHIVED';


UPdate  SBR.VALUE_MEANINGS set CHANGE_NOTE=null,ASL_NAME='DRAFT NEW'
where VM_IDSEQ in(
select  VM.VM_IDSEQ
from SBR.VALUE_MEANINGS VM,
MDSR_VM_DUP_REF REF
where   VM.VM_ID=REF.VM_ID
and VM.ASL_NAME='RETIRED ARCHIVED');


select* 
--delete 
from
 sbrext.ac_att_cscsi_ext 
 where date_created>SYSDATE-25
 
 select* 
 --delete 
 from  SBR.DEFINITIONS  where date_created>SYSDATE-25;
 
  select* 
 --delete 
 from  SBR.DESIGNATIONS  where date_created>SYSDATE-25;
 
 
 create table MDSR_VM_DUP_REF_OLD  as select*
  --delete 
 from MDSR_VM_DUP_REF 
 
 
 DROP TABLE SBR.MDSR_VM_DUP_REF CASCADE CONSTRAINTS;

CREATE TABLE SBR.MDSR_VM_DUP_REF
(
  FIN_VM                NUMBER,
  FIN_IDSEQ             VARCHAR2(36 BYTE),
  VM_ID                 NUMBER                  NOT NULL,
  VM_IDSEQ              VARCHAR2(36 BYTE)       NOT NULL,
  CONDR_IDSEQ           VARCHAR2(36 BYTE),
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  DATE_CREATED          DATE,
  RUN_NUMBER            NUMBER,
  DES                   ,
  DEFN                ,
  DES_CL               ,
  DEFN_CL               VARCHAR2(10 BYTE),  
  PROC                  VARCHAR2(10 BYTE)
  
)

(DES IS NULL or  DEFN IS NULL or  DES_CL IS NULL or  DEFN_CL IS NULL or   PROC IS NULL)


INSERT INTO SBR.MDSR_VM_DUP_REF
(FIN_VM  ,
  FIN_IDSEQ ,
  VM_ID,
  VM_IDSEQ,
  CONDR_IDSEQ ,
  LONG_NAME ,
  PREFERRED_DEFINITION ,
  DATE_CREATED ,
  RUN_NUMBER )
SELECT FIN_VM  ,
  FIN_IDSEQ ,
  VM_ID,
  VM_IDSEQ,
  CONDR_IDSEQ ,
  LONG_NAME ,
  PREFERRED_DEFINITION ,
  DATE_CREATED ,
  RUN_NUMBER
FROM source_table
[WHERE conditions];


select  
a.FIN_VM,b.VM_IDSEQ,a.vm_id,a.VM_IDSEQ,a.CONDR_IDSEQ,NULL,NULL,SYSDATE, 1
from
(select  FIN_VM,vm_id,VM_IDSEQ,CONDR_IDSEQ
from (
select max(VM_ID) over (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM,VM_ID,VM_IDSEQ,CONDR_IDSEQ
from 
SBR.VALUE_MEANINGS 
where   UPPER(ASL_NAME) not like '%RETIRED%'
and CONDR_IDSEQ='F37D0428-BBB6-6787-E034-0003BA3F9857'
and CONDR_IDSEQ is not NULL)
where FIN_VM<>VM_ID 
MINUS
select  FIN_VM,vm_id,VM_IDSEQ,CONDR_IDSEQ from MDSR_VM_DUP_REF where CONDR_IDSEQ is not null)a,
SBR.VALUE_MEANINGS b
where a.FIN_VM=b.VM_ID;


select  
a.FIN_VM,b.VM_IDSEQ,a.vm_id,a.VM_IDSEQ,NULL,a.LONG_NAME,a.PREFERRED_DEFINITION,SYSDATE, 11
from
(select  FIN_VM,vm_id,VM_IDSEQ,LONG_NAME,PREFERRED_DEFINITION
from (
select max(VM_ID) over (partition by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) order by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) ) as FIN_VM,

VM_ID,VM_IDSEQ,UPPER(trim(LONG_NAME))LONG_NAME,UPPER(trim(PREFERRED_DEFINITION))PREFERRED_DEFINITION,CONDR_IDSEQ
from 
SBR.VALUE_MEANINGS 
where   UPPER(ASL_NAME) not like '%RETIRED%'
and UPPER(trim(LONG_NAME))='9 MONTHS' 
and CONDR_IDSEQ is null)
where FIN_VM<>VM_ID 
MINUS
select  FIN_VM,vm_id,VM_IDSEQ,LONG_NAME,PREFERRED_DEFINITION from MDSR_VM_DUP_REF
where    CONDR_IDSEQ is null)a,
SBR.VALUE_MEANINGS b
where a.FIN_VM=b.VM_ID;


select*from definitions where AC_IDSEQ in('191D1B3C-14B6-C5C0-E050-BB89AD435B0C','F4E980E1-076F-A6E4-E040-BB89AD437CE2')
order by DEFINITION;

select*from designations where AC_IDSEQ in('191D1B3C-14B6-C5C0-E050-BB89AD435B0C')
order by NAME;



exec SBR.MDSR_INSERT_VM_DUP_REF;
exec SBR.MDSR_CLEAR_DUP_VM_NAME_STEP1;

 select *
from 
MDSR_VM_DUP_REF REF
where    CONDR_IDSEQ is   NULL;  ('2509CE87-C62E-5C23-E044-0003BA3F9857','61B7CA8A-8254-77AC-E040-BB89AD430888')

select FIN_VM,FIN_IDSEQ,REF.VM_ID,REF.VM_IDSEQ,VM.CONTE_IDSEQ,REF.long_name,REF.PREFERRED_DEFINITION,VM.version
from SBR.VALUE_MEANINGS VM,
MDSR_VM_DUP_REF REF
where   VM.VM_IDSEQ=REF.VM_IDSEQ
and  (REF.DES IS NULL or  REF.DEFN IS NULL or  REF.DES_CL IS NULL or  REF.DEFN_CL IS NULL or REF.PROC IS NULL);


select MAX_RN, RWN,DESIG_IDSEQ,CONTE_IDSEQ,NAME,DETL_NAME,LAE_NAME,date_created from
(select max(rownum) over (partition by CONTE_IDSEQ,trim(upper(NAME)),trim(upper(DETL_NAME)),trim(upper(LAE_NAME)) 
order by trim(upper(NAME)),trim(upper(DETL_NAME)),trim(upper(LAE_NAME)),CONTE_IDSEQ ) as MAX_RN,
rownum RWN,DESIG_IDSEQ,CONTE_IDSEQ,NAME,DETL_NAME,LAE_NAME,date_created 
from designations where AC_IDSEQ in (select  
VM_IDSEQ
from
(select  FIN_VM,vm_id,VM_IDSEQ,LONG_NAME,PREFERRED_DEFINITION
from (
select max(VM_ID) over (partition by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) order by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) ) as FIN_VM,

VM_ID,VM_IDSEQ,UPPER(trim(LONG_NAME))LONG_NAME,UPPER(trim(PREFERRED_DEFINITION))PREFERRED_DEFINITION,CONDR_IDSEQ
from 
SBR.VALUE_MEANINGS 
where   UPPER(ASL_NAME) not like '%RETIRED%'

and CONDR_IDSEQ is null)
where FIN_VM<>VM_ID )))
--('2509CE87-C62E-5C23-E044-0003BA3F9857','61B7CA8A-8254-77AC-E040-BB89AD430888'))
where MAX_RN=RWN
order by NAME;

select*from definitions where AC_IDSEQ in ('2509CE87-C62E-5C23-E044-0003BA3F9857','61B7CA8A-8254-77AC-E040-BB89AD430888');


select  
VM_IDSEQ
from
(select  FIN_VM,vm_id,VM_IDSEQ,LONG_NAME,PREFERRED_DEFINITION
from (
select max(VM_ID) over (partition by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) order by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) ) as FIN_VM,

VM_ID,VM_IDSEQ,UPPER(trim(LONG_NAME))LONG_NAME,UPPER(trim(PREFERRED_DEFINITION))PREFERRED_DEFINITION,CONDR_IDSEQ
from 
SBR.VALUE_MEANINGS 
where   UPPER(ASL_NAME) not like '%RETIRED%'

and CONDR_IDSEQ is null)
where FIN_VM<>VM_ID );


select MAX_RN, RWN,DEFIN_IDSEQ,CONTE_IDSEQ,DEFINITION,DEFL_NAME,LAE_NAME,date_created,AC_IDSEQ from
(select max(rownum) over (partition by CONTE_IDSEQ,UPPER(trim(DEFINITION)),UPPER(trim(DEFL_NAME)),UPPER(trim(LAE_NAME))
 order by UPPER(trim(DEFINITION)),UPPER(trim(DEFL_NAME)),UPPER(trim(LAE_NAME)) ) as MAX_RN,
rownum RWN,DEFIN_IDSEQ,CONTE_IDSEQ,DEFINITION,DEFL_NAME,LAE_NAME,date_created ,AC_IDSEQ
from SBR.DEFINITIONS where AC_IDSEQ in (select  
VM_IDSEQ
from
(select  FIN_VM,vm_id,VM_IDSEQ,LONG_NAME,PREFERRED_DEFINITION
from (
select max(VM_ID) over (partition by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) order by UPPER(trim(LONG_NAME)),UPPER(trim(PREFERRED_DEFINITION)) ) as FIN_VM,

VM_ID,VM_IDSEQ,UPPER(trim(LONG_NAME))LONG_NAME,UPPER(trim(PREFERRED_DEFINITION))PREFERRED_DEFINITION,CONDR_IDSEQ
from 
SBR.VALUE_MEANINGS 
where   UPPER(ASL_NAME) not like '%RETIRED%'

and CONDR_IDSEQ is null)
where FIN_VM<>VM_ID )))
where MAX_RN=RWN;


select *from value_meanings where VM_IDSEQ='79456F37-8A99-1948-E040-BB89AD435A58'