select* from SBREXT.MDSR_VM_DUP_REF order by concepts_code


exec SBREXT.MDSR_INSERT_VM_FINAL_DUP_REF


select* from SBREXT.MDSR_VM_DUP_ERR where date_created>SYSDATE-1


 delete from SBREXT.MDSR_VM_DUP_REF

  

INSERT INTO SBREXT.MDSR_VM_DUP_REF
(FIN_VM,FIN_IDSEQ ,VM_ID,VM_IDSEQ,CONCEPTS_CODE,CONCEPTS_NAME,LONG_NAME, PROCESSED,CONCEPT_SYNONYM ,CONDR_IDSEQ)--)
 select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ,name CONCEPTS_CODE,CONCEPT_NAME,VM_NAME,'FINAL','CONCEPT' ,'1346457D-3BD2-2201-E044-0003BA3F9857'
 from
(
select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,VM_NAME,CONCEPT_NAME,CONDR_IDSEQ,VM_IDSEQ ,name from
(
select VM_ID,VM_IDSEQ,VM.LONG_NAME VM_NAME,CN.LONG_NAME CONCEPT_NAME,VM.CONDR_IDSEQ,name
from SBR.VALUE_MEANINGS VM,
SBREXT.CON_DERIVATION_RULES_EXT DER,
SBREXT.CONCEPTS_EXT CN,
(
 select COUNT(*),CONDR_IDSEQ from SBR.VALUE_MEANINGS VM
 where   UPPER(ASL_NAME) not like '%RETIRED%' AND CONDR_IDSEQ is not null
 GROUP BY CONDR_IDSEQ HAVING COUNT(*)>1
 )DUP
 where   VM.CONDR_IDSEQ=DER.CONDR_IDSEQ
 AND VM.CONDR_IDSEQ=DUP.CONDR_IDSEQ
 and DER.NAME=CN.PREFERRED_NAME
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%'
 AND TRIM(UPPER(VM.LONG_NAME)) =TRIM(UPPER(CN.LONG_NAME))
 AND instr(DER.NAME,'C49668')>0
 ))
 where FIN_VM=VM_ID
 UNION
  select   FIN_VM ,VM_IDSEQ FIN_IDSEQ,VM_ID,VM_IDSEQ,name CONCEPTS_CODE,CONCEPT_NAME,VM_NAME,CONDR_IDSEQ,'FINAL','CONCEPT',SYSDATE from
(
select  max(VM_ID) over  (partition by CONDR_IDSEQ order by CONDR_IDSEQ ) as FIN_VM 
,VM_ID,VM_NAME,CONCEPT_NAME,name,CONDR_IDSEQ,VM_IDSEQ from
(
 SELECT VM_ID,VM_IDSEQ,name,trim(UPPER(CONCEPT_NAME))CONCEPT_NAME,trim(UPPER(LONG_NAME)) VM_NAME,VM.CONDR_IDSEQ,trim(UPPER(vm.DESCRIPTION)) VM_DESCRIPTION
FROM  SBR.VALUE_MEANINGS VM,
(SELECT M.CONDR_IDSEQ,name, LISTAGG(M.LONG_NAME,' ') WITHIN GROUP (ORDER BY M.ELM_ORDER) as CONCEPT_NAME
FROM  (select CONDR_IDSEQ,name,spl.preferred_name,ELM_ORDER,LONG_NAME
from
(select distinct
 CONDR_IDSEQ,name,
  trim(regexp_substr(replace(replace(name,'Rh Negative Blood Group','C76252'),'Rh Positive Blood Group','C76251'), '[^:]+', 1, levels.column_value)) as preferred_name,levels.column_value ELM_ORDER
from 
 (select *from SBREXT.CON_DERIVATION_RULES_EXT  
 where  instr(name,':')>0) t,
 table(cast(multiset(select level from dual connect by level <= length (regexp_replace(t.name, '[^:]+')) + 1) as sys.OdciNumberList))
  levels) spl,
  sbrext.concepts_ext  c
  where spl.preferred_name=c.preferred_name) M
GROUP BY name,M.CONDR_IDSEQ)VW,
 (select count(*),CONDR_IDSEQ from SBR.VALUE_MEANINGS VM 
 where  UPPER(ASL_NAME) not like '%RETIRED%'
 having count(*)>1GROUP BY CONDR_IDSEQ )DR
where    VW.CONDR_IDSEQ=VM.CONDR_IDSEQ
AND  VW.CONDR_IDSEQ=DR.CONDR_IDSEQ
and UPPER(ASL_NAME) not like '%RETIRED%'
and (trim(UPPER(VM.LONG_NAME))=trim(UPPER(CONCEPT_NAME))||'S' or trim(UPPER(VM.LONG_NAME))=trim(UPPER(CONCEPT_NAME)))
and instr(NAME,'C45255')=0 ))
 where FIN_VM=VM_ID
 
 ORDER BY 4,2 desc ;
 
 
 1346457D-3BD2-2201-E044-0003BA3F9857
 
 drop  INDEX SBREXT.MDSR_VM_DUP_REF_IDX
 CREATE INDEX SBREXT.MDSR_VM_DUP_REF_IDX ON SBREXT.MDSR_VM_DUP_REF(VM_ID,decode(CONDR_IDSEQ,NULL,'A',CONDR_IDSEQ))
 
 
 
  select distinct Rf.FIN_VM,Rf.FIN_IDSEQ ,vm.VM_ID,vm.VM_IDSEQ,CONCEPTS_CODE,CONCEPTS_NAME,vm.LONG_NAME,rf.CONDR_IDSEQ ,
  UPPER(trim(vm.PREFERRED_DEFINITION)) PREFERRED_DEFINITION
 FROM SBREXT.MDSR_VM_DUP_REF RF ,SBR.VALUE_MEANINGS VM 
 where Vm.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%' 
AND Rf.FIN_IDSEQ<>vm.VM_IDSEQ 
 AND  instr(CONCEPTS_CODE,':')=0
 and instr(CONCEPTS_CODE,'C45255')=0 
 and CONCEPTS_CODE='C41261'
 --and instr(CONCEPTS_CODE,'C67382')>0
 and (SBREXT.MDSR_GET_CONCEPT_SYN(CONCEPTS_CODE,vm.LONG_NAME)=0
 and trim(UPPER(replace(replace(VM.LONG_NAME,CONCEPTS_CODE,''),':','')))<>trim(UPPER(CONCEPTS_NAME)))
 
 
 
select distinct Rf.FIN_VM,Rf.FIN_IDSEQ ,vm.VM_ID,vm.VM_IDSEQ,CONCEPTS_CODE,CONCEPTS_NAME,vm.LONG_NAME,rf.CONDR_IDSEQ ,
UPPER(trim(vm.PREFERRED_DEFINITION))PREFERRED_DEFINITION
 FROM SBREXT.MDSR_VM_DUP_REF RF ,SBR.VALUE_MEANINGS VM 
 where Vm.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%' 
 AND Rf.FIN_IDSEQ<>vm.VM_IDSEQ
 AND  instr(CONCEPTS_CODE,':')>0
 and instr(CONCEPTS_CODE,'C45255')=0 
 and (TRIM(upper(CONCEPTS_NAME))<>trim(upper(vm.LONG_NAME)) and trim(UPPER(VM.LONG_NAME))<>trim(UPPER(CONCEPTS_NAME))||'S' )
 
 
 
 select distinct Rf.FIN_VM,Rf.FIN_IDSEQ ,vm.VM_ID,vm.VM_IDSEQ,CONCEPTS_CODE,CONCEPTS_NAME,vm.LONG_NAME,rf.CONDR_IDSEQ ,
UPPER(trim(vm.PREFERRED_DEFINITION))PREFERRED_DEFINITION
 FROM SBREXT.MDSR_VM_DUP_REF RF ,SBR.VALUE_MEANINGS VM 
 where Vm.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%' 
-- AND Rf.FIN_IDSEQ<>vm.VM_IDSEQ
 AND  instr(CONCEPTS_CODE,':')>0
 and instr(CONCEPTS_CODE,'C45255')=0 
  and CONCEPT_SYNONYMis='NON'
  and CONCEPTS_CODE='C25685:C17649'
  
  
  CONDR_IDSEQ
  
  
  
  select distinct lon from SBREXT.MDSR_VM_DUP_REF where CONCEPTS_CODE='C25685:C17649'
  
  
   select distinct Rf.FIN_VM,Rf.FIN_IDSEQ ,vm.VM_ID,vm.VM_IDSEQ,CONCEPTS_CODE,CONCEPTS_NAME,vm.LONG_NAME,rf.CONDR_IDSEQ ,
UPPER(trim(vm.PREFERRED_DEFINITION))PREFERRED_DEFINITION
 FROM SBREXT.MDSR_VM_DUP_REF RF ,SBR.VALUE_MEANINGS VM 
 where Vm.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%' 
 --AND Rf.FIN_IDSEQ<>vm.VM_IDSEQ
 AND  instr(CONCEPTS_CODE,':')>0
 and instr(CONCEPTS_CODE,'C45255')=0 
  and CONCEPTS_CODE='C25685:C17649'
  order by rf.CONDR_IDSEQ,vm.VM_ID;
  
  
     select distinct CONCEPTS_CODE, UPPER(trim(CONCEPTS_NAME)),UPPER(trim(vm.LONG_NAME)),PR
 FROM SBREXT.MDSR_VM_DUP_REF RF ,SBR.VALUE_MEANINGS VM 
 where Vm.CONDR_IDSEQ=RF.CONDR_IDSEQ
 AND UPPER(VM.ASL_NAME) not like '%RETIRED%' 
 --AND Rf.FIN_IDSEQ<>vm.VM_IDSEQ
 AND  instr(CONCEPTS_CODE,':')=0
 and instr(CONCEPTS_CODE,'C45255')=0 
 --and (TRIM(upper(CONCEPTS_NAME))<>trim(upper(vm.LONG_NAME)) and SBREXT.MDSR_GET_CONCEPT_SYN(CONCEPTS_CODE,vm.LONG_NAME)<>1
 --and trim(UPPER(replace(replace(VM.LONG_NAME,CONCEPTS_CODE,''),':','')))<>trim(UPPER(CONCEPTS_NAME)))
   and CONCEPT_SYNONYM ='NON'
order by UPPER(trim(CONCEPTS_NAME));
-- order by CONCEPTS_CODE,rf.CONDR_IDSEQ,vm.VM_ID;
 
 --delete from  SBREXT.MDSR_VM_DUP_REF where UPPER(trim(CONCEPTS_NAME)) is null--FIN_IDSEQ =VM_IDSEQ;
 
 
 select* from  SBREXT.MDSR_VM_DUP_REF where CONCEPT_SYNONYM ='NON'
 order by CONCEPTS_CODE;
 
 select count(*) from SBREXT.MDSR_VM_DUP_REF order by concepts_code;


exec SBREXT.MDSR_INSERT_VM_FINAL_DUP_REF


select* from SBREXT.MDSR_VM_DUP_ERR where date_created>SYSDATE-1
  