select VM.vm_id,VM.long_name,VM.PREFERRED_DEFINITION,VM.VM_IDSEQ, DF.CONTE_IDSEQ,DEFINITION,DEFL_NAME,LAE_NAME
--,AC.ACA_IDSEQ,  AC.CS_CSI_IDSEQ,AC.ATL_NAME
from
 SBR.VALUE_MEANINGS VM
 ,SBR.DEFINITIONS DF
, sbrext.ac_att_cscsi_ext AC
where VM.vm_id=5037694
AND VM.VM_IDSEQ=DF.AC_IDSEQ
--and FIN_VM=i.FIN_VM


AND AC.att_idseq = DF.DEF_idseq
and DF.CONTE_IDSEQ=i.conte_idseq
and DEFINITION=i.DEFINITION
and DF.DETL_NAME=i.DETL_NAME
order by DEFINITION,DEFL_NAME,LAE_NAME;