DROP TABLE SBREXT.MDSR_CDE_XML_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CDE_XML_TEMP
(
  TYPE          VARCHAR2(30 BYTE),
  FILE_NAME     VARCHAR2(200 BYTE),
  CREATED_DATE  DATE,
  TEXT          CLOB
)
LOB (TEXT) STORE AS BASICFILE (
  TABLESPACE  SBREXT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG
(
  ERROR_MSG             VARCHAR2(3000 BYTE),
  UPLOAD_DATE           DATE,
  PREFERRED_NAME        VARCHAR2(300 BYTE),
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE),
  EVS_SOURCE            VARCHAR2(300 BYTE),
  ORIGIN                VARCHAR2(300 BYTE),
  SOURCE_DEFINITION     VARCHAR2(3000 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_CONCEPTS_EXT_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_TEMP
(
  PREFERRED_NAME        VARCHAR2(300 BYTE),
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE),
  EVS_SOURCE            VARCHAR2(300 BYTE),
  ORIGIN                VARCHAR2(300 BYTE),
  SOURCE_DEFINITION     VARCHAR2(3000 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_CONTEXT_XML_GROUP CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CONTEXT_XML_GROUP
(
  CONTEXT    VARCHAR2(30 BYTE),
  C_SEQ      NUMBER,
  GROUP_NUM  NUMBER
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_DESIGNATIONS_LOAD_ERR CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_DESIGNATIONS_LOAD_ERR
(
  PUBLICID                       VARCHAR2(15 BYTE),
  VERSION                        VARCHAR2(5 BYTE),
  LONGNAME                       VARCHAR2(500 BYTE),
  TYPE                           VARCHAR2(10 BYTE),
  CREATEDBY                      VARCHAR2(30 BYTE),
  DATECREATED                    VARCHAR2(20 BYTE),
  DATEMODIFIED                   VARCHAR2(20 BYTE),
  ID                             VARCHAR2(50 BYTE),
  LANGUAGENAME                   VARCHAR2(100 BYTE),
  MODIFIEDBY                     VARCHAR2(30 BYTE),
  NAME                           VARCHAR2(2000 BYTE),
  TYPE2                          VARCHAR2(20 BYTE),
  DESIGNATIONCLASSSCHEMEITEMCOL  VARCHAR2(100 BYTE),
  CONTEXT                        VARCHAR2(30 BYTE),
  AC_IDSEQ                       CHAR(36 BYTE),
  CONTE_IDSEQ                    CHAR(36 BYTE),
  COMMENTS                       VARCHAR2(200 BYTE),
  LOADDATE                       DATE
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_DESIGNATIONS_UPLOAD CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_DESIGNATIONS_UPLOAD
(
  PUBLICID                       VARCHAR2(15 BYTE),
  VERSION                        VARCHAR2(5 BYTE),
  LONGNAME                       VARCHAR2(500 BYTE),
  TYPE                           VARCHAR2(10 BYTE),
  CREATEDBY                      VARCHAR2(30 BYTE),
  DATECREATED                    VARCHAR2(20 BYTE),
  DATEMODIFIED                   VARCHAR2(20 BYTE),
  ID                             VARCHAR2(50 BYTE),
  LANGUAGENAME                   VARCHAR2(100 BYTE),
  MODIFIEDBY                     VARCHAR2(30 BYTE),
  NAME                           VARCHAR2(2000 BYTE),
  TYPE2                          VARCHAR2(20 BYTE),
  DESIGNATIONCLASSSCHEMEITEMCOL  VARCHAR2(100 BYTE),
  CONTEXT                        VARCHAR2(30 BYTE),
  AC_IDSEQ                       CHAR(36 BYTE),
  CONTE_IDSEQ                    CHAR(36 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_FB_QUESTION_MVW CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_FB_QUESTION_MVW
(
  FORM_ID                 NUMBER                NOT NULL,
  FORM_IDSEQ              CHAR(36 BYTE)         NOT NULL,
  MOD_IDSEQ               CHAR(36 BYTE),
  QUES_IDSEQ              CHAR(36 BYTE)         NOT NULL,
  QUES_ID                 NUMBER                NOT NULL,
  QUES_VERSION            NUMBER(4,2)           NOT NULL,
  QTL_NAME                VARCHAR2(30 BYTE)     NOT NULL,
  CONTE_IDSEQ             CHAR(36 BYTE)         NOT NULL,
  Q_CONTEXT               VARCHAR2(30 BYTE),
  DATE_CREATED            DATE                  NOT NULL,
  DATE_MODIFIED           DATE,
  DISPLAY_ORDER           NUMBER(6),
  WORKFLOW                VARCHAR2(20 BYTE)     NOT NULL,
  Q_PREFERRED_NAME        VARCHAR2(30 BYTE)     NOT NULL,
  Q_PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)   NOT NULL,
  DE_IDSEQ                CHAR(36 BYTE),
  Q_LONG_NAME             VARCHAR2(4000 BYTE),
  DATECREATED             DATE                  NOT NULL,
  QUESTION                VARCHAR2(2000 BYTE),
  DE_VERSION              NUMBER(4,2),
  DE_LONG_NAME            VARCHAR2(255 BYTE),
  CDE_ID                  NUMBER,
  VD_IDSEQ                CHAR(36 BYTE),
  DE_WORKFLOW             VARCHAR2(20 BYTE),
  DE_PREFERRED_NAME       VARCHAR2(30 BYTE),
  D_PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  DE_CONTEXT              VARCHAR2(30 BYTE),
  EDITABLE_IND            CHAR(3 BYTE)          NOT NULL,
  MANDATORY_IND           VARCHAR2(3 BYTE),
  Q_INSTRUCTION           VARCHAR2(2000 BYTE),
  ISDERIVED               VARCHAR2(5 BYTE),
  MULTIVALUE              VARCHAR2(3 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_FB_QUEST_MODULE_MVW CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_FB_QUEST_MODULE_MVW
(
  MOD_IDSEQ             CHAR(36 BYTE)           NOT NULL,
  CRF_IDSEQ             CHAR(36 BYTE),
  MOD_ID                NUMBER                  NOT NULL,
  VERSION               NUMBER(4,2)             NOT NULL,
  CONTE_IDSEQ           CHAR(36 BYTE)           NOT NULL,
  WORKFLOW              VARCHAR2(20 BYTE)       NOT NULL,
  PREFERRED_NAME        VARCHAR2(30 BYTE)       NOT NULL,
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)     NOT NULL,
  LONG_NAME             VARCHAR2(4000 BYTE),
  LATEST_VERSION_IND    VARCHAR2(3 BYTE),
  DISPLAY_ORDER         NUMBER(6),
  REPEAT_NO             NUMBER,
  CONTEXT               VARCHAR2(30 BYTE)       NOT NULL,
  MOD_INSTRUCTION       VARCHAR2(2000 BYTE),
  USAGETYPE             VARCHAR2(11 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_FB_VALID_VALUE_MVW CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_FB_VALID_VALUE_MVW
(
  FORM_ID                   NUMBER              NOT NULL,
  FORM_IDSEQ                CHAR(36 BYTE)       NOT NULL,
  MOD_ID                    NUMBER              NOT NULL,
  MOD_IDSEQ                 CHAR(36 BYTE)       NOT NULL,
  QUEST_ID                  NUMBER              NOT NULL,
  QUEST_IDSEQ               CHAR(36 BYTE)       NOT NULL,
  VV_IDSEQ                  CHAR(36 BYTE)       NOT NULL,
  "TRIM(QV.DISPLAY_ORDER)"  VARCHAR2(40 BYTE),
  LONG_NAME                 VARCHAR2(4000 BYTE),
  MEANING_TEXT              VARCHAR2(2000 BYTE),
  DESCRIPTION_TEXT          VARCHAR2(2000 BYTE),
  VM_ID                     NUMBER,
  VM_VERSION                NUMBER,
  VP_IDSEQ                  CHAR(36 BYTE),
  INSTRUCTION               VARCHAR2(2000 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_PROC_ERR_LOG CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_PROC_ERR_LOG
(
  SP_NAME       CHAR(36 BYTE),
  TABLE_NAME    CHAR(40 BYTE),
  TABLE_ID      CHAR(100 BYTE),
  ERROR_TEXT    VARCHAR2(2000 BYTE),
  DATE_CREATED  DATE
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_PROTOCOLS_ERR_LOG CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_PROTOCOLS_ERR_LOG
(
  PROTOCOL_ID           VARCHAR2(500 BYTE),
  INSERT_DATE           DATE,
  ERROR_TEXT            VARCHAR2(1000 BYTE),
  PREFERRED_NAME        VARCHAR2(300 BYTE),
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE),
  CONTEXT               CHAR(360 BYTE),
  WORKFLOW              VARCHAR2(360 BYTE),
  ORIGIN                VARCHAR2(1000 BYTE),
  TYPE                  VARCHAR2(2400 BYTE),
  PHASE                 VARCHAR2(300 BYTE),
  LEAD_ORG              VARCHAR2(1000 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_PROTOCOLS_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_PROTOCOLS_TEMP
(
  PREFERRED_NAME        VARCHAR2(300 BYTE),
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE),
  CONTEXT               CHAR(360 BYTE),
  WORKFLOW              VARCHAR2(360 BYTE),
  ORIGIN                VARCHAR2(1000 BYTE),
  TYPE                  VARCHAR2(2400 BYTE),
  PROTOCOL_ID           VARCHAR2(500 BYTE),
  PHASE                 VARCHAR2(300 BYTE),
  LEAD_ORG              VARCHAR2(1000 BYTE)
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_CDE_XML_TEMP FOR SBREXT.MDSR_CDE_XML_TEMP;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_CONCEPTS_EXT_ERROR_LOG FOR SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_CONCEPTS_EXT_TEMP FOR SBREXT.MDSR_CONCEPTS_EXT_TEMP;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_DESIGNATIONS_LOAD_ERR FOR SBREXT.MDSR_DESIGNATIONS_LOAD_ERR;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_DESIGNATIONS_UPLOAD FOR SBREXT.MDSR_DESIGNATIONS_UPLOAD;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_FB_QUESTION_MVW FOR SBREXT.MDSR_FB_QUESTION_MVW;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_FB_QUEST_MODULE_MVW FOR SBREXT.MDSR_FB_QUEST_MODULE_MVW;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_FB_VALID_VALUE_MVW FOR SBREXT.MDSR_FB_VALID_VALUE_MVW;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_PROC_ERR_LOG FOR SBREXT.MDSR_PROC_ERR_LOG;


CREATE OR REPLACE PUBLIC SYNONYM MDSR_PROTOCOLS_ERR_LOG FOR SBREXT.MDSR_PROTOCOLS_ERR_LOG;


GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.MDSR_PROC_ERR_LOG TO DER_USER;

GRANT SELECT ON SBREXT.MDSR_CDE_XML_TEMP TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_CONCEPTS_EXT_TEMP TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_DESIGNATIONS_LOAD_ERR TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_DESIGNATIONS_UPLOAD TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_FB_QUESTION_MVW TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_FB_QUEST_MODULE_MVW TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_FB_VALID_VALUE_MVW TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_PROTOCOLS_ERR_LOG TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_PROTOCOLS_TEMP TO PUBLIC;

GRANT SELECT ON SBREXT.MDSR_PROC_ERR_LOG TO READONLY;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SBREXT.MDSR_PROC_ERR_LOG TO SBR WITH GRANT OPTION;
