CREATE TABLE SBREXT.MDSR_REDCAP_PROTOCOL_CSV
(
  VARIABLE_FIELD_NAME  VARCHAR2(400 BYTE),
  FORM_NAME            VARCHAR2(400 BYTE),
  SECTION              VARCHAR2(3000 BYTE),
  SECTION_SEQ          NUMBER,
  SECTION_Q_SEQ        NUMBER,
  FIELD_TYPE           VARCHAR2(100 BYTE),
  CHOICES              CLOB,
  FIELD_NOTE           VARCHAR2(100 BYTE),
  QUESTION             NUMBER,
  TEXT_VALID_TYPE      VARCHAR2(60 BYTE),
  TEXT_VALID_MIN       VARCHAR2(60 BYTE),
  TEXT_VALID_MAX       VARCHAR2(60 BYTE),
  IDENTIFIER           VARCHAR2(100 BYTE),
  LOGIC                VARCHAR2(4000 BYTE),
  REQUIRED             VARCHAR2(20 BYTE),
  CUSTOM_ALIGNMENT     VARCHAR2(100 BYTE),
  MATRIX_GROUP_NAME    VARCHAR2(100 BYTE),
  MATRIX_RANK          NUMBER(6,2),
  Q_NMB_SERV           NUMBER,
  PROTOCOL             VARCHAR2(40 BYTE),
  FIELD_LABEL          VARCHAR2(4000 BYTE),
  INSTRUCTIONS         VARCHAR2(4000 CHAR),
  VAL_MIN              VARCHAR2(100 BYTE),
  VAL_MAX              VARCHAR2(100 BYTE),
  VAL_TYPE             VARCHAR2(100 BYTE),
  QUESTION_CSV         CLOB,
  FORM_QUESTION        VARCHAR2(2000 BYTE),
  QUEST_TB_QUESTION    VARCHAR2(4000 BYTE),
  FORM_NAME_NEW        VARCHAR2(400 BYTE),
  FORM_Q_NUM           NUMBER,
  LOAD_SEQ             NUMBER
);

create index SBREXT.MDSR_PROTO_Q_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (PROTOCOL);
create index SBREXT.MDSR_FN_Q_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (form_name_new);
create index SBREXT.MDSR_FQ_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (question);
create index SBREXT.MDSR_FSEC_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (section_seq);
create index SBREXT.MDSR_FSEC_Q_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (section_q_seq);
create index SBREXT.MDSR_QLOAD_Q_INDX on SBREXT.MDSR_REDCAP_PROTOCOL_CSV (LOAD_SEQ);
CREATE TABLE SBREXT.MDSR_QUEST_CONTENTS_UPDATE_ERR
(
  QC_ID         NUMBER,
  QTL_NAME      VARCHAR2(30 BYTE),
  ERR_MSG       VARCHAR2(2000 BYTE),
  DATE_CREATED  DATE
);
CREATE TABLE SBREXT.MDSR_QUEST_CONTENTS_REDCAP_BK
(
  QC_IDSEQ              CHAR(36 BYTE),
  QC_ID                 NUMBER,
  VERSION               NUMBER(4,2),
  QTL_NAME              VARCHAR2(30 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  LONG_NAME             VARCHAR2(4000 BYTE),
  DATE_CREATED          DATE,
  CREATED_BY            VARCHAR2(30 BYTE),
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  DATE_INSERTED         DATE,
  UPDATED_FIELD         VARCHAR2(50 BYTE)
);
GRANT SELECT ON SBREXT.MDSR_REDCAP_PROTOCOL_CSV TO PUBLIC;
GRANT SELECT ON SBREXT.MDSR_QUEST_CONTENTS_REDCAP_BK TO PUBLIC;
GRANT SELECT ON SBREXT.MDSR_QUEST_CONTENTS_UPDATE_ERR TO PUBLIC;
CREATE TABLE SBREXT.MSDREDCAP_FORM_CSV
(
  PROTOCOL              VARCHAR2(40 BYTE),
  FORM_NAME_NEW         VARCHAR2(800 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  PROTOCOL_NAME         VARCHAR2(500 BYTE),
  INSTRUCTIONS          VARCHAR2(2000 BYTE),
  LOAD_SEQ              NUMBER
);
CREATE TABLE SBREXT.MSDREDCAP_SECTION_CSV
(
  PROTOCOL       VARCHAR2(40 BYTE),
  FORM_NAME      VARCHAR2(800 BYTE),
  SECTION_SEQ    NUMBER,
  SECTION_Q_SEQ  NUMBER,
  QUESTION       NUMBER,
  SECTION        VARCHAR2(2000 BYTE),
  SECTION_NEW    VARCHAR2(2000 BYTE),
  INSTRUCTION    VARCHAR2(2000 BYTE),
  LOAD_SEQ       NUMBER
);
CREATE TABLE SBREXT.MSDREDCAP_VALUE_CODE_CSV
(
  PROTOCOL      VARCHAR2(50 BYTE),
  FORM_NAME     VARCHAR2(255 BYTE),
  QUESTION      NUMBER,
  VAL_NAME      VARCHAR2(500 BYTE),
  VAL_VALUE     VARCHAR2(500 BYTE),
  VAL_ORDER     NUMBER,
  ELM_ORDER     VARCHAR2(50 BYTE),
  PIPE_NUM      NUMBER,
  VAL_VAL_NAME  CLOB,
  RUN_NUM       NUMBER
);
GRANT SELECT ON SBREXT.MSDREDCAP_FORM_CSV TO PUBLIC;
GRANT SELECT ON SBREXT.MSDREDCAP_SECTION_CSV TO PUBLIC;
GRANT SELECT ON SBREXT.MSDREDCAP_VALUE_CODE_CSV TO PUBLIC;

create index SBREXT.MDSR_VV_PROTO_Q_INDX on SBREXT.MSDREDCAP_VALUE_CODE_CSV (PROTOCOL);
create index SBREXT.MDSR_VVFN_Q_INDX on SBREXT.MSDREDCAP_VALUE_CODE_CSV (form_name);
create index SBREXT.MDSR_VVQ_INDX on SBREXT.MSDREDCAP_VALUE_CODE_CSV (question);
create index SBREXT.MDSR_VVQLOAD_Q_INDX on SBREXT.MSDREDCAP_VALUE_CODE_CSV (LOAD_SEQ);
