OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\CONTACT_UPLOAD\CONTACTLOAD.csv' "str '\r'"

INTO TABLE SBR.META_UPLOAD_CONTACT
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(Public_ID ,
VERSION ,
RANK_ORDER,
LNAME,
FNAME,
CROLE,
CTL_NAME,
ORGANISATION,
CYBER_ADDRESS
)

