set serveroutput on size 1000000
SPOOL cadsrmeta-618t.log
DROP TABLE SBR.META_UPLOAD_ERROR_LOG
/
DROP TABLE SBR.META_UPLOAD_CONTACT
/
CREATE TABLE SBR.META_UPLOAD_ERROR_LOG
(
  ERROR_MSG             VARCHAR2(3000 BYTE),
  UPLOAD_DATE           DATE,
  PROCEDURE_NAME        VARCHAR2(40 BYTE),
  RECORD_ID             VARCHAR2(300 BYTE)
)
/
CREATE TABLE SBR.META_UPLOAD_CONTACT
(Public_ID   NUMBER,
VERSION               NUMBER(4,2) ,
RANK_ORDER     NUMBER(3)  ,
ORGANISATION    VARCHAR2(100 BYTE),
LNAME VARCHAR2(36 BYTE),
FNAME VARCHAR2(36 BYTE),
CROLE  VARCHAR2(36 BYTE),
CTL_NAME  VARCHAR2(36 BYTE),
CYBER_ADDRESS  VARCHAR2(255 BYTE), 
COMMENTS VARCHAR2(500 BYTE) )
/
CREATE OR REPLACE PUBLIC SYNONYM   META_UPLOAD_ERROR_LOG FOR SBR.META_UPLOAD_ERROR_LOG;
CREATE OR REPLACE PUBLIC SYNONYM META_UPLOAD_CONTACT FOR SBR.META_UPLOAD_CONTACT;
CREATE OR REPLACE PUBLIC SYNONYM CT_CD_VMS_BKUP FOR SBR.CT_CD_VMS_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_DATA_ELEMENTS_BKUP FOR SBR.CT_DATA_ELEMENTS_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_VALUE_MEANINGS_BKUP FOR SBR.CT_VALUE_MEANINGS_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_DATA_ELEMENT_CONCEPTS_BKUP FOR SBR.CT_DATA_ELEMENT_CONCEPTS_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_PERMISSIBLE_VALUES_BKUP FOR SBR.CT_PERMISSIBLE_VALUES_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_REF_DOC_BKUP FOR SBR.CT_REF_DOC_BKUP;
CREATE OR REPLACE PUBLIC SYNONYM CT_VALUE_DOMAINS_BKUP FOR SBR.CT_VALUE_DOMAINS_BKUP;
GRANT SELECT ON META_UPLOAD_ERROR_LOG TO PUBLIC;
GRANT SELECT ON META_UPLOAD_CONTACT TO PUBLIC;
GRANT SELECT ON CT_CD_VMS_BKUP TO PUBLIC;
GRANT SELECT ON CT_DATA_ELEMENTS_BKUP TO PUBLIC;
GRANT SELECT ON CT_DATA_ELEMENT_CONCEPTS_BKUP TO PUBLIC;
GRANT SELECT ON CT_VALUE_MEANINGS_BKUP TO PUBLIC;
GRANT SELECT ON CT_PERMISSIBLE_VALUES_BKUP TO PUBLIC;
GRANT SELECT ON CT_REF_DOC_BKUP TO PUBLIC;
GRANT SELECT ON CT_VALUE_DOMAINS_BKUP TO PUBLIC;
SPOOL OFF


