CREATE TABLE SBR.META_UPLOAD_ERROR_LOG
(
  ERROR_MSG             VARCHAR2(3000 BYTE),
  UPLOAD_DATE           DATE,
  PROCEDURE_NAME        VARCHAR2(40 BYTE),
  RECORD_ID             VARCHAR2(300 BYTE)
)
/
CREATE TABLE SBR.META_UPLOAD_CONTACT
(Public_ID   NUMBER,
VERSION               NUMBER(4,2) ,
RANK_ORDER     NUMBER(3)  ,
ORGANISATION    VARCHAR2(100 BYTE),
LNAME VARCHAR2(36 BYTE),
FNAME VARCHAR2(36 BYTE),
CROLE  VARCHAR2(36 BYTE),
CTL_NAME  VARCHAR2(36 BYTE),
CYBER_ADDRESS  VARCHAR2(255 BYTE), 
COMMENTS VARCHAR2(500 BYTE) )
/


