CREATE TABLE SBREXT.DEV11G_OBJECTS
(
  OWNER        VARCHAR2(30 BYTE),
  OBJECT_TYPE  VARCHAR2(19 BYTE),
  OBJECT_NAME  VARCHAR2(128 BYTE)
)
;
CREATE TABLE SBREXT.DEV11G_PRIVS
(
  OWNER       VARCHAR2(30 BYTE)             ,
  GRANTEE     VARCHAR2(30 BYTE)   ,
  TABLE_NAME  VARCHAR2(30 BYTE)          ,
  PRIVILEGE   VARCHAR2(40 BYTE)     
);
CREATE TABLE SBREXT.DEV12C_OBJECTS
(
  OWNER        VARCHAR2(30 BYTE),
  OBJECT_TYPE  VARCHAR2(19 BYTE),
  OBJECT_NAME  VARCHAR2(128 BYTE)
);
CREATE TABLE SBREXT.DEV12C_PRIVS
(
  OWNER       VARCHAR2(30 BYTE)   ,
  GRANTEE     VARCHAR2(30 BYTE)  ,
  TABLE_NAME  VARCHAR2(30 BYTE)  ,
  PRIVILEGE   VARCHAR2(40 BYTE)  );
