OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\ORACLE12c\ALL_PRIVS12C.csv' "str '\r'" 

INTO TABLE SBREXT.DEV12C_PRIVS
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS                 
   ( OWNER ,    
    grantee,
	table_name,
	PRIVILEGE
    )
	
	