DROP TABLE SBR.MDSR_TABLE_COLUMN_SPCHAR_LOG;
drop TABLE SBR.TRRG_TRM_SPC_ERROR_LOG;
CREATE TABLE SBR.TRRG_TRM_SPC_ERROR_LOG
(
  TRIGGER_NAME        CHAR(50 BYTE)                  NOT NULL,
  TABLE_NAME        CHAR(60 BYTE)                  NOT NULL,
  DATE_MODIFIED  DATE,
  ERROR_TEXT     VARCHAR2(500 BYTE)
);
CREATE OR REPLACE PUBLIC SYNONYM TRRG_TRM_SPC_ERROR_LOG FOR SBR.TRRG_TRM_SPC_ERROR_LOG;
GRANT SELECT ON SBR.TRRG_TRM_SPC_ERROR_LOG TO PUBLIC;

CREATE TABLE SBR.MDSR_TABLE_COLUMN_SPCHAR_LOG
(
  TABLE_NAME        CHAR(50 BYTE)  , 
  PK_NAME       CHAR(50 BYTE)    ,               
  PK_VAL       CHAR(50 BYTE)    ,              
  COLUMN_NAME  CHAR(30 BYTE)    ,
  COLUMN_VAL    VARCHAR2(4000 BYTE),
  PROCESS_IND   VARCHAR2(30),
  DATE_CREATED DATE
);
CREATE OR REPLACE PUBLIC SYNONYM TRRG_TRM_SPC_ERROR_LOG FOR SBR.MDSR_TABLE_COLUMN_SPCHAR_LOG;
GRANT SELECT ON SBR.MDSR_TABLE_COLUMN_SPCHAR_LOG TO PUBLIC;
