
CREATE TABLE SBREXT.CT_QUEST_CONTENTS_EXT_BKUP
( QC_IDSEQ              CHAR(36 BYTE)           NOT NULL,
  PREFERRED_NAME        VARCHAR2(30 BYTE),
  DATE_MODIFIED         DATE,
  DATE_INSERT           DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE),
  LONG_NAME             VARCHAR2(4000 BYTE)
)
/
CREATE TABLE SBREXT.CT_VALID_VALUES_ATT_EXT_BKUP
( QC_IDSEQ          CHAR(36 BYTE)               NOT NULL,
  MEANING_TEXT      VARCHAR2(2000 BYTE),
  DATE_MODIFIED     DATE,
  DATE_INSERT           DATE,
  MODIFIED_BY       VARCHAR2(30 BYTE),
  DESCRIPTION_TEXT  VARCHAR2(2000 BYTE)
)
/
CREATE TABLE SBREXT.META_SPCHAR_ERROR_LOG
( SP_NAME              CHAR(36 BYTE)           NOT NULL,
  DATE_MODIFIED         DATE,
  ERROR_TEXT             VARCHAR2(4000 BYTE)
)
/
CREATE TABLE SBR.CT_PERMISSIBLE_VALUES_BKUP
(
  PV_IDSEQ             CHAR(36 BYTE)            NOT NULL,
  VALUE                VARCHAR2(255 BYTE)       NOT NULL,
  SHORT_MEANING        VARCHAR2(255 BYTE)       NOT NULL,
  MEANING_DESCRIPTION  VARCHAR2(2000 BYTE),
  DATE_MODIFIED        DATE,
  DATE_INSERT           DATE,
  MODIFIED_BY          VARCHAR2(30 BYTE),
  VM_IDSEQ             CHAR(36 BYTE)            NOT NULL
)
/
CREATE TABLE SBR.CT_VALUE_MEANINGS_BKUP
( SHORT_MEANING         VARCHAR2(255 BYTE)      ,
  DESCRIPTION           VARCHAR2(2000 BYTE),
  DATE_MODIFIED         DATE,
  DATE_INSERT           DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  VM_IDSEQ              CHAR(36 BYTE)          ,
  PREFERRED_NAME        VARCHAR2(30 BYTE)      ,
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)    ,
  LONG_NAME             VARCHAR2(255 BYTE),
  VERSION               NUMBER                  ,
  VM_ID                 NUMBER                ,
  CHANGE_NOTE           VARCHAR2(2000 BYTE)
)
/
grant select,insert,update  on SBREXT.META_SPCHAR_ERROR_LOG to SBR
/
CREATE TABLE SBR.CT_VALUE_DOMAINS_BKUP
( VD_IDSEQ              CHAR(36 BYTE)          ,
  VERSION               NUMBER(4,2)             ,
  PREFERRED_NAME        VARCHAR2(30 BYTE)       , 
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)    ,  
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),  
  ORIGIN                VARCHAR2(240 BYTE),
  VD_ID                 NUMBER                ,
  CONDR_IDSEQ           CHAR(36 BYTE),
  LONG_NAME             VARCHAR2(255 BYTE),
  DATE_INSERT  DATE
)
/
CREATE TABLE SBR.CT_CD_VMS_BKUP
( CV_IDSEQ       CHAR(36 BYTE)                ,
  CD_IDSEQ       CHAR(36 BYTE)                 ,
  SHORT_MEANING  VARCHAR2(255 BYTE)           ,
  DESCRIPTION    VARCHAR2(2000 BYTE),
  DATE_INSERT   DATE                          ,  
  DATE_MODIFIED  DATE,
  MODIFIED_BY    VARCHAR2(30 BYTE),
  VM_IDSEQ       CHAR(36 BYTE)              
)
/
CREATE TABLE SBR.CT_REF_DOC_BKUP
( RD_IDSEQ       CHAR(36 BYTE)                  ,
  NAME           VARCHAR2(255 BYTE)             ,
  ORG_IDSEQ      CHAR(36 BYTE),  
  AC_IDSEQ       CHAR(36 BYTE),
  ACH_IDSEQ      CHAR(36 BYTE),
  AR_IDSEQ       CHAR(36 BYTE),
  DOC_TEXT       VARCHAR2(4000 BYTE),  
  DATE_MODIFIED  DATE,
  DATE_INSERT           DATE,
  MODIFIED_BY    VARCHAR2(30 BYTE),
  COMMENTS VARCHAR2(255 BYTE) 
)
/
CREATE TABLE SBREXT.CT_PROPERTIES_EXT_BKUP
(
  PROP_IDSEQ            CHAR(36 BYTE)          ,
  PREFERRED_NAME        VARCHAR2(30 BYTE)      ,
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)    ,
  CONTE_IDSEQ           CHAR(36 BYTE)          ,
  VERSION               NUMBER(4,2)            ,
  ASL_NAME              VARCHAR2(20 BYTE)      ,  
  CHANGE_NOTE           VARCHAR2(2000 BYTE),
  DEFINITION_SOURCE     VARCHAR2(2000 BYTE),
  DATE_INSERT           DATE, 
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  PROP_ID               NUMBER                   
)
/
CREATE TABLE SBR.CT_DATA_ELEMENTS_BKUP
(
  DE_IDSEQ              CHAR(36 BYTE)          ,
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)     ,
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  DATE_INSERT  DATE
)
/
CREATE TABLE SBR.CT_DATA_ELEMENT_CONCEPTS_BKUP
(
  DEC_IDSEQ             CHAR(36 BYTE)           ,
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)       ,
  LONG_NAME             VARCHAR2(255 BYTE),
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  DATE_INSERT  DATE
)
/
CREATE TABLE SBREXT.CT_OBJECT_CLASSES_EXT_BKUP
(
  OC_IDSEQ              CHAR(36 BYTE)          ,
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)  ,
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  DATE_INSERT  DATE
)
/
CREATE TABLE SBREXT.CT_REPRESENTATIONS_EXT_BKUP
(
  REP_IDSEQ             CHAR(36 BYTE)          ,
  LONG_NAME             VARCHAR2(255 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(2000 BYTE)    ,
  DATE_MODIFIED         DATE,
  MODIFIED_BY           VARCHAR2(30 BYTE),
  DATE_INSERT  DATE
)
/
