OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\META\JIRA-762\NewDesignationsTypes.csv' "str '\r'"
INTO TABLE SBR.DESIGNATION_TYPES_TEMP
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS 
( DETL_NAME   CHAR(20) ,
  DESCRIPTION CHAR(60), 
  COMMENTS  CHAR(2000))


