set serveroutput on size 1000000
SPOOL cadsrmeta-660.log
ALTER TABLE SC_CONTEXTS
DROP CONSTRAINT SCC_CONTE_FK;
ALTER TABLE SC_CONTEXTS
ADD CONSTRAINT SCC_CONTE_FK FOREIGN KEY (CONTE_IDSEQ)
REFERENCES SBR.CONTEXTS(CONTE_IDSEQ) ON DELETE CASCADE ENABLE;
delete from SBR.SC_CONTEXTS where SCL_NAME = 'CTD-2_SC';
delete from SBR.CONTEXTS where name = 'CTD-2';
commit;
SPOOL OFF
