set serveroutput on size 1000000
SPOOL cadsrmeta-580a.log
CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_TEMP
(    PREFERRED_NAME        VARCHAR2(300 BYTE)      ,
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE)    
 )
/
CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG
( ERROR_MSG             VARCHAR2(3000 BYTE) ,
 UPLOAD_DATE            DATE,
  PREFERRED_NAME        VARCHAR2(300 BYTE)      ,
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE)    
)
/
SPOOL OFF