set serveroutput on size 1000000
SPOOL cadsrmeta-580a.log
CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_TEMP
(    PREFERRED_NAME        VARCHAR2(300 BYTE)      ,
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE)    
 )
/
CREATE TABLE SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG
( ERROR_MSG             VARCHAR2(3000 BYTE) ,
 UPLOAD_DATE            DATE,
  PREFERRED_NAME        VARCHAR2(300 BYTE)      ,
  LONG_NAME             VARCHAR2(500 BYTE),
  PREFERRED_DEFINITION  VARCHAR2(3000 BYTE)    
)
/
CREATE OR REPLACE PUBLIC SYNONYM MDSR_CONCEPTS_EXT_TEMP FOR SBREXT.MDSR_CONCEPTS_EXT_TEMP;
CREATE OR REPLACE PUBLIC SYNONYM MDSR_CONCEPTS_EXT_ERROR_LOG FOR SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG;
GRANT SELECT ON MDSR_CONCEPTS_EXT_TEMP TO PUBLIC;
GRANT SELECT ON MDSR_CONCEPTS_EXT_ERROR_LOG TO PUBLIC;
SPOOL OFF