drop TYPE SBREXT.HARMONY_DOC_REF_LIST_T  ;
drop TYPE SBREXT.HARMONY_DEF_LIST_T  ;
drop TYPE SBREXT.HARMONY_FORM_CDE_LIST_T ;
drop TYPE SBREXT.HARMONY_DESIGN_LIST_T ;
drop  TYPE SBREXT.HARMONY_VD_TYPE_LIST_T     ;
drop  TYPE SBREXT.HARMONY_FORM_PROTO_LIST_T ;
drop TYPE SBREXT.HARMONY_VM_LIST_T ;

drop TYPE SBREXT.HARMONY_DESIGN_T        ;
drop TYPE SBREXT.HARMONY_FORM_CDE_T    ;
drop TYPE SBREXT.HARMONY_DEFINITION_T ;
drop TYPE SBREXT.HARMONY_DOC_REF_T    ;
drop TYPE SBREXT.HARMONY_VD_TYPE_T    ;
drop TYPE SBREXT.HARMONY_FORM_PROTO_T  ;
drop TYPE SBREXT.HARMONY_VM_T  ;