select QF.QC_ID FormId,QE.QTL_NAME,QE.QC_ID ElementId,QE.version Element_version,QE.long_name Element_long_name,QE.ASL_NAME Status,QE.DE_IDSEQ,DE.CDE_ID,DE.long_name,DE.QUESTION
from SBREXT.QUEST_CONTENTS_EXT  QE,
SBREXT.QUEST_CONTENTS_EXT  QF,
SBR.DATA_ELEMENTS DE
 where (QF.QC_IDSEQ=QE.DN_CRF_IDSEQ or QE.QC_IDSEQ=QF.QC_IDSEQ)and
 QE.CONTE_IDSEQ='8F119EA6-BC32-2319-E040-BB89AD431E26'
 and QF.CONTE_IDSEQ='8F119EA6-BC32-2319-E040-BB89AD431E26'
 and QE.DE_IDSEQ=DE.DE_IDSEQ(+)
 and QF.QTL_NAME='CRF';