DROP TABLE SBREXT.MDSR_CDE_XML_REPORT_ERR CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CDE_XML_REPORT_ERR
(
  FILE_NAME         VARCHAR2(50 BYTE),
  REPORT_ERROR_TXT  VARCHAR2(1100 BYTE),
  DATE_PROCESSED    DATE
)
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE SBREXT.MDSR_CDE_XML_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SBREXT.MDSR_CDE_XML_TEMP
(
  TYPE          VARCHAR2(30 BYTE),
  FILE_NAME     VARCHAR2(200 BYTE),
  CREATED_DATE  DATE,
  TEXT          CLOB
)
LOB (TEXT) STORE AS BASICFILE (
  TABLESPACE  SBREXT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE SBREXT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
