set serveroutput on size 1000000
SPOOL cadsrmeta-686b.log

CREATE OR REPLACE PUBLIC SYNONYM MDSR_DESIGNATIONS_LOAD_ERR FOR SBREXT.MDSR_DESIGNATIONS_LOAD_ERR;
CREATE OR REPLACE PUBLIC SYNONYM MDSR_DESIGNATIONS_UPLOAD FOR SBREXT.MDSR_DESIGNATIONS_UPLOAD;
CREATE OR REPLACE PUBLIC SYNONYM MDSR_DES_UPLOAD_VW FOR SBREXT.MDSR_DES_UPLOAD_VW;

GRANT SELECT  ON MDSR_DESIGNATIONS_LOAD_ERR TO PUBLIC;
GRANT SELECT  ON MDSR_DESIGNATIONS_UPLOAD TO PUBLIC;
GRANT SELECT  ON MDSR_DES_UPLOAD_VW TO PUBLIC;
exec SBREXT.MDSR_CEATE_DESIGNATIONS('DATA_ELEMENTS');
SPOOL OFF