set serveroutput on size 1000000
SPOOL cadsrmeta-cona.log
ALTER TABLE  SBREXT.MDSR_CONCEPTS_EXT_TEMP
 ADD (
  EVS_SOURCE            VARCHAR2(300 BYTE),
  ORIGIN                VARCHAR2(300 BYTE),
  SOURCE_DEFINITION     VARCHAR2(3000 BYTE)
    );
ALTER TABLE  SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG
 ADD (
  EVS_SOURCE            VARCHAR2(300 BYTE),
  ORIGIN                VARCHAR2(300 BYTE),
  SOURCE_DEFINITION     VARCHAR2(3000 BYTE)
    );	
delete from SBREXT.MDSR_CONCEPTS_EXT_TEMP;
delete from SBREXT.MDSR_CONCEPTS_EXT_ERROR_LOG;
SPOOL OFF